[package]
name = "piserverrust"
version = "0.0.1"
authors = ["Kyle Kewley <kylek61294@gmail.com>"]

[dependencies.piservercore]
git = "https://github.com/kylekewley/piservercore.git"

[dependencies]
capnp = "0.2.4"
